export const heroCategory = [
  {
    id: 1,
    img: "images/vehicle_icon.png",
    name: "vehicles",
    path: "/vehicles",
  },
  {
    id: 2,
    img: "images/fashion_icon.png",
    name: "fashions",
    path: "/fashions",
  },
  {
    id: 1,
    img: "images/jobs-1.png",
    name: "jobs",
    path: "jobs",
  },
  {
    id: 1,
    img: "images/real_estate_icon.png",
    name: "real estate",
    path: "estate",
  },
  {
    id: 1,
    img: "images/services_icon.png",
    name: "services",
    path: "/services",
  },
  {
    id: 1,
    img: "images/pets_icon.png",
    name: "pets",
    path: "/pets",
  },
];

export const discCategory = [
  {
    id: 1,
    name: "devices",
    subText: "Innovative Devices for Modern Living",
    addText: "Buy and Sell Devices with Ease",
    description:
      "Discover the easiest way to buy and sell devices! Whether you're looking for the latest tech or upgrading your gadgets, our platform connects buyers and sellers for a seamless experience. Shop smart, sell fast, and find great deals on smartphones, laptops, tablets, and more.",
    img: "images/category_1.jpg",
    path: "/cat1",
  },
  {
    id: 2,
    name: "cars",
    addText: "Buy, Sell, and Trade Cars Today",
    subText: "Discover Cutting-Edge Car Technology",
    description:
      "Buy and sell cars effortlessly with our trusted platform. Explore a wide range of vehicles, from budget-friendly options to luxury models. Whether you're upgrading or selling, connect with buyers and sellers for a fast, secure, and hassle-free car trading experience.",
    img: "images/category_2.jpg",
    path: "/cat2",
  },
  {
    id: 3,
    name: "pets",
    addText: "Find the Right Pet for Your Purpose",
    subText: "The Ultimate Pet Care Resource",
    description:
      "Find your perfect pet or rehome your furry friends easily. Our platform connects pet lovers with breeders and sellers for a safe, reliable experience. Explore a variety of pets—from dogs and cats to exotic animals—and make pet adoption and sales smooth and simple",
    img: "images/category_3.jpg",
    path: "/cat3",
  },
  {
    id: 4,
    name: "real estate",
    subText: "Your Gateway to Real Estate Excellence",
    addText: "Explore the World of Real Estate",
    description:
      "Buy and sell real estate with confidence on our trusted platform. Whether you're searching for your dream home, looking to invest, or selling property, we provide an easy, secure experience for both buyers and sellers. Explore a wide range of properties—homes, commercial spaces, and land—tailored to your needs.",
    img: "images/category_3-1.jpg",
    path: "/cat4",
  },
  {
    id: 5,
    name: "community",
    subText: "Join a Vibrant Community of Like-minded Individuals",
    addText: "Connect, Share, and Grow Together",
    description:
      "Join our community marketplace for a seamless buying and selling experience. Connect with local buyers and sellers to discover great deals on everything from household items to electronics, furniture, and more. Empower your neighborhood with a trusted, easy-to-use platform for all your buying and selling needs.",
    img: "images/category_3-2.jpg",
    path: "/cat5",
  },
  {
    id: 6,
    name: "for kids",
    subText: "A World of Fun and Learning for Kids",
    addText: "Your Kids' Marketplace: Buy & Sell",
    description:
      "Buy and sell kids' products with ease on our trusted marketplace. From clothing and toys to baby gear and educational items, connect with other parents and families to find great deals. Whether you're upgrading or downsizing, our platform makes it simple to shop and sell high-quality kids' products.",
    img: "images/category_3-3.jpg",
    path: "/cat6",
  },
  {
    id: 7,
    name: "gardening",
    subText: "Unleash Your Inner Gardener",
    addText: "Discover the Joy of Gardening",
    description:
      "Buy and sell gardening supplies, tools, and plants effortlessly on our platform. Whether you're a seasoned gardener or just starting out, discover a variety of seeds, pots, tools, and outdoor decor. Connect with fellow gardening enthusiasts to find great deals and grow your green space.",
    img: "images/category_3-4.jpg",
    path: "/cat7",
  },
];

export const listing = [
  {
    id: 1,
    name: "Iphone 13 Pro case",
    price: "200",
    img: "images/listing/card_1-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 2,
    name: "Wallie Toy",
    price: "1000",
    img: "images/listing/card_2-360x240.jpg",
    views: "1075",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 3,
    name: "Little kittens",
    price: "1500",
    img: "images/listing/card_5-360x240.jpg",
    views: "487",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 4,
    name: "Macbook Pro 16",
    price: "34000",
    img: "images/listing/card_6-360x240.jpg",
    views: "234",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 5,
    name: "Collection of clothes",
    price: "2000",
    img: "images/listing/listing_1-360x240.jpeg",
    views: "3452",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 6,
    name: "Mercedez-Benz S-Class",
    price: "2000000",
    img: "images/listing/car-new-1-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: true,
  },
  {
    id: 7,
    name: "Apartment with Pool",
    price: "45000",
    img: "images/listing/promo-resort-360x240.jpg",
    views: "455",
    location: "Nairobi, Kenya",
    featured: true,
  },
  {
    id: 8,
    name: "New Teddy Bear",
    price: "500",
    img: "images/listing/baby-009-360x240.jpg",
    views: "345",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 9,
    name: "White Truck",
    price: "6000000",
    img: "images/listing/truck-7-360x240.jpg",
    views: "670",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 10,
    name: "Team Leader",
    price: "20000",
    img: "images/listing/jobs-003-360x240.jpg",
    views: "267",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 11,
    name: "Wedding Decorations",
    price: "14000",
    img: "images/listing/wedding-7-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: true,
  },
  {
    id: 12,
    name: "Car Mechanical Repair",
    price: "10000",
    img: "images/listing/automotive-services-1-360x240.jpg",
    views: "678",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 13,
    name: "Mercez-Benz S-Class",
    price: "2000000",
    img: "images/listing/car-7-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 14,
    name: "Handbags with Style",
    price: "2000",
    img: "images/listing/clothing-001-360x240.jpg",
    views: "2000",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 15,
    name: "Little Bright Dog",
    price: "15000",
    img: "images/listing/animals-004-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 16,
    name: "Playstation 5",
    price: "50000",
    img: "images/listing/playstation-6-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 17,
    name: "Garden and Home Decor",
    price: "10000",
    img: "images/listing/garden-001-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
  {
    id: 18,
    name: "Apple iPhone 11 Pro Max",
    price: "120000",
    img: "images/listing/phone-010-360x240.jpg",
    views: "200",
    location: "Nairobi, Kenya",
    featured: false,
  },
];

export const membership = [
  {
    id: 1,
    plan: "Free",
    price: "0.00",
    listing: 5,
    galleryImagesPerListing: 2,
    featuredListing: 0,
    businessHourNotAllowed: true,
    enquiryFormNotAllowed: true,
    membershipBadgeNotAllowed: true,
  },
  {
    id: 2,
    plan: "Weekly",
    price: "1,280.00",
    listing: 10,
    galleryImagesPerListing: 5,
    featuredListing: 5,
    businessHourNotAllowed: false,
    enquiryFormNotAllowed: false,
    membershipBadgeNotAllowed: false,
  },
  {
    id: 3,
    plan: "Monthly",
    price: "6,400.00",
    listing: 20,
    galleryImagesPerListing: 10,
    featuredListing: 10,
    businessHourNotAllowed: false,
    enquiryFormNotAllowed: false,
    membershipBadgeNotAllowed: false,
  },
  {
    id: 4,
    plan: "Yearly",
    price: "12,800.00",
    listing: 50,
    galleryImagesPerListing: 20,
    featuredListing: 20,
    businessHourNotAllowed: false,
    enquiryFormNotAllowed: false,
    membershipBadgeNotAllowed: false,
  },
];

export const team = [
  {
    id: 1,
    name: "Wade Warren",
    title: "Founder & CEO",
    img: "images/media/tam11714911266.jpg",
  },
  {
    id: 2,
    name: "Wade Warren",
    title: "Founder & CEO",
    img: "images/media/tam21714911266.jpg",
  },
  {
    id: 3,
    name: "Wade Warren",
    title: "Founder & CEO",
    img: "images/media/tam31714913557.jpg",
  },
  {
    id: 4,
    name: "Wade Warren",
    title: "Founder & CEO",
    img: "images/media/tam41714913557.jpg",
  },
];
